### ISSUE TITLE
RKE2ControlPlane version mismatch

### ISSUE THREAD

**Issue by will-darkwolf** [rancher-sandbox/cluster-api-provider-rke2#101]
**What happened:**
Following the quickstart instructions to deploy a simple AWS RKE2 cluster. When trying to apply the generate rke2-docker-example.yaml file, I received `Error from server (BadRequest): error when creating "rke2-docker-example.yaml": RKE2ControlPlane in version "v1alpha1" cannot be handled as a RKE2ControlPlane: strict decoding error: unknown field "spec.version"`

**What did you expect to happen:**
The cluster deployment to begin according to the quickstart guide.

**How to reproduce it:**

**Anything else you would like to add:**
```
➜  rke2 kubectl apply -f rke2-docker-example.yaml 
namespace/example created
cluster.cluster.x-k8s.io/capd-rke2-test created
dockercluster.infrastructure.cluster.x-k8s.io/capd-rke2-test-my-cluster created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/controlplane created
machinedeployment.cluster.x-k8s.io/worker-md-0 created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/worker created
rke2config.bootstrap.cluster.x-k8s.io/capd-rke2-test-agent created
Error from server (BadRequest): error when creating "rke2-docker-example.yaml": RKE2ControlPlane in version "v1alpha1" cannot be handled as a RKE2ControlPlane: strict decoding error: unknown field "spec.version"
```
```
apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capd-rke2-test
  namespace: example
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: RKE2ControlPlane
    name: capd-rke2-test-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: capd-rke2-test-my-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: capd-rke2-test-my-cluster
  namespace: example
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: RKE2ControlPlane
metadata:
  name: capd-rke2-test-control-plane
  namespace: example
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    name: controlplane
  nodeDrainTimeout: 2m
  replicas: 3
  version: v1.25.3+rke2r1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: controlplane
  namespace: example
spec:
  template:
    spec: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: worker-md-0
  namespace: example
spec:
  clusterName: capd-rke2-test
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: capd-rke2-test
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: RKE2Config
          name: capd-rke2-test-agent
          namespace: example
      clusterName: capd-rke2-test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: worker
        namespace: example
      version: v1.25.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: worker
  namespace: example
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: RKE2Config
metadata:
  name: capd-rke2-test-agent
  namespace: example
spec:
  agentConfig:
    version: v1.25.3+rke2r1
```
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- clusterctl version: &version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"58770484dee6c99c10e32c06652e9f9643f78e9e", GitTreeState:"clean", BuildDate:"", GoVersion:"go1.20.1", Compiler:"gc", Platform:"darwin/arm64"}
- Kubectl Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:49:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
- Kustomize Version: v4.5.7
- Kubectl Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6+k3s1", GitCommit:"9176e03c5788e467420376d10a1da2b6de6ff31f", GitTreeState:"clean", BuildDate:"2023-01-26T00:30:33Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/arm64"}

**rke provider version:**
  - name: "docker"
    url: "https://github.com/belgaied2/cluster-api/releases/v1.3.3-cabpr-fix/infrastructure-components.yaml"
    type: "InfrastructureProvider"
  - name: "rke2"
    url: "https://github.com/rancher-sandbox/cluster-api-provider-rke2/releases/v0.1.0-alpha.1/bootstrap-components.yaml"
    type: "BootstrapProvider"
  - name: "rke2"
    url: "https://github.com/rancher-sandbox/cluster-api-provider-rke2/releases/v0.1.0-alpha.1/control-plane-components.yaml"
    type: "ControlPlaneProvider"
- OS (e.g. from `/etc/os-release`):
