### ISSUE TITLE
convert AdditionalUserData.Config  field in CRD from string to dict

### ISSUE THREAD

**Issue by FrancoisKlieberOrange** [rancher-sandbox/cluster-api-provider-rke2#167]
**Describe the solution you'd like:**
We would like to have in CRD _RKE2ConfigTemplate_ and _RKE2ControlPlane_ the field AdditionalUserData.Config as dict instead of string.

**Why do you want this feature:**
We are using Helm as template engine. We use multiple values file to override specific part of the chart.
We would like to have a one to one matching between types of CRD used in the chart and type in the value of the chart.

If the field, AdditionalUserData.Config,  was a dict, we could benefit from native helm features to merge override values files.

**Comment by tmmorin** [comment]
Yes, generally speaking, even beyond our specific case where Helm is used, having this field be a dict will allow fine-grained composition/patching to be feasible.   Today it's not possible to do anything inside the `config` text blob with `kustomize` either.

**Comment by richardcase** [comment]
This would be a breaking API change. The API is alpha level which means according to the k8s API guarantees we can make breaking API changes but feels like we should find a way to introduce this without breaking.

There are a coupld of ways we can do this:

1. Bump the API version so that we have conversion webhooks. Then we can convert the existing string field to a dict (assuming we can parse the string easily)
2. We introduce a new field in `AdditionalUserData` for the dic, mark the existing `Config` field as deprecated, and then add a check in the validation webhook to stop people supplying values for both fields.

**Comment by tmmorin** [comment]
I would have been reading to say that "break the API in v1alpha2 _without_ any conversion" would not be problematic, at least from Sylva standpoint.

I don't have any idea of what is the easiest to implement, either look equally valid.

One thing perhaps worth noting: today we have this `strict`  boolean flag at the same level as `confg`, documented as "Strict controls if Config should be strictly parsed. If so, warnings are treated as errors.". If feels like it may relate to the discussion here: 
* what would this field mean if we change `config` into a dict ? is it still relevant ? shouldn't it be deprecated ?
* if the implementation chosen involves converting the config text into a dict, after parsing as YAML ? how should `strict: false` be interpreted ?

**Comment by Danil-Grigorev** [comment]
Hi @tmmorin, currently the easiest way to provide User templating is to add an additional field with a list of user configs to pass, similarly to [kubeadm bootstrapper](https://github.com/kubernetes-sigs/cluster-api/blob/8bef2f37fa884a30789df0117e448983d877294f/bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go#L533). Do you require some additional templating capabilities on top of that? Generally if using ignition configuration, the data passed to the `AdditionalUserData` will be merged with templated ignition config, allowing to add patches on top, and it might be better for you to use this mechanism longer term.

**Comment by richardcase** [comment]
I've been thinking about this and my understaing is that given these 2 separate value files:

file1:
```yaml
config:
  users:
    - name: ubuntu
      groups: users
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      lock_passwd: false
      passwd: "put your password hash here" # (copy pasted from /etc/shadow or created with "mkpasswd" --method=SHA-512 --stdin")
      ssh_authorized_keys:
        - ssh-rsa AAAA...... YOUR KEY HERE ....UqnQ==
```

file2:

```yaml
config:
  packages:
    - git
```

Then we should be able to compose the both of them (using kustomize/helm) into a RKE2Config[Template] like this:

```yaml
...
config:
  users:
    - name: ubuntu
      groups: users
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      lock_passwd: false
      passwd: "put your password hash here" # (copy pasted from /etc/shadow or created with "mkpasswd" --method=SHA-512 --stdin")
      ssh_authorized_keys:
        - ssh-rsa AAAA...... YOUR KEY HERE ....UqnQ==
  packages:
    - git
...
```

So i'm wondering if the new filed can be `map[string]string` or something similar?
