### ISSUE TITLE
RKE2 upgrade fails

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/cluster-api-provider-rke2#193]
**What happened:**

Testing out an RKE2 (on CAPO infra) workload cluster upgrade (started from a cluster of 3 CP + 1 worker nodes in v1.25.14+rke2r1 and wanted to achieve  3 CP + 2 worker nodes in v1.26.9+rke2r1) results in a node rolling update where the new version CP node will refer to an old CP node (deleted by CAPI rolling update) endpoint, which is no longer reachable, breaking the ETCD leader election.

**What did you expect to happen:**

Its expected the upgrade completes without failure

**How to reproduce it:**

How to reproduce on CAPO

```yaml
# environment-values/my-environment-values/values.yaml
---
units:
  workload-cluster:
    enabled: true
    helmrelease_spec:
      values:
        cluster:
          # k8s_version: "v1.25.14+rke2r1"       # before apply.sh
          k8s_version: "v1.26.9+rke2r1"       # after apply.sh
          capo:
            # image_name: "ubuntu-jammy-plain-rke2-1.25.14-0.1.0"       # before apply.sh
            image_name: "ubuntu-jammy-plain-rke2-1.26.9-0.0.12"       # after apply.sh
          control_plane_replicas: 3

          machine_deployments:
            md0:
              # replicas: 1       # used for v1.25.14, before apply.sh
              replicas: 2       # used for v1.26.19, after apply.sh
              capo:
                failure_domain: dev-az
```

and running:

```
root@~/sylva-core # ./apply.sh environment-values/my-environment-values
:
 ✓ Kustomization/default/flux-webui - Resource is ready: Flux Web UI can be reached at https://flux.sylva (flux.sylva must resolve to 192.168.128.193)
⢎⡰ HelmRelease/workload-cluster/calico - GetLastReleaseFailed - failed to get last release revision
⢎⡰ HelmRelease/workload-cluster/calico-crd - GetLastReleaseFailed - failed to get last release revision
⢎⡰ HelmRelease/workload-cluster/cinder-csi - GetLastReleaseFailed - failed to get last release revision
⢎⡰ HelmRelease/workload-cluster/ingress-nginx - GetLastReleaseFailed - failed to get last release revision
⢎⡰ HelmRelease/workload-cluster/metallb - GetLastReleaseFailed - failed to get last release revision
⢎⡰ HelmRelease/workload-cluster/monitoring - GetLastReleaseFailed - failed to get last release revision
⢎⡰ HelmRelease/workload-cluster/monitoring-crd - GetLastReleaseFailed - failed to get last release revision
⢎⡰ Kustomization/default/workload-cluster - Progressing - Reconciliation in progress
⢎⡰ Kustomization/workload-cluster/namespace-defs - ReconciliationFailed - Namespace/cattle-monitoring-system dry-run failed: failed to get API group resources: unable to retrieve the complete list of server APIs: v1: Get "https://192.168.129.147:6443/api/v1?timeout=30s": dial tcp 192.168.129.147:6443: connect: no route to host
 ✗ Command timeout exceeded
root@~/sylva-core#
```

**Anything else you would like to add:**

[This is the original issue](https://gitlab.com/sylva-projects/sylva-core/-/issues/695) for the Sylva project. See this for additional information

**Environment:**

- rke provider version:
- OS (e.g. from `/etc/os-release`):
