### ISSUE TITLE
RKE2 bootstrap provider does not actually pass etcd extra args to etcd

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/cluster-api-provider-rke2#234]
**What happened:**

When creating a cluster with etcd extra args they are not not being passed to etcd.

For example:

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: RKE2ControlPlane
metadata:
  annotations:
    meta.helm.sh/release-name: cluster
    meta.helm.sh/release-namespace: sylva-system
...
  name: management-cluster-control-plane
  namespace: sylva-system
...
spec:
....
  replicas: 1
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  serverConfig:
    cni: calico
    disableComponents: {}
    etcd:
      backupConfig: {}
      customConfig:
        extraArgs:
        - quota-backend-bytes=5368709120
        - auto-compaction-mode=periodic
        - auto-compaction-retention=5h

```

The extra args are not used

**Anything else you would like to add:**

See the [downstream issue](https://gitlab.com/sylva-projects/sylva-core/-/issues/857) for further details

**Environment:**

- rke provider version:
- OS (e.g. from `/etc/os-release`):
