### ISSUE TITLE
Impossible to set rolloutStrategy to rollingUpdate

### ISSUE THREAD

**Issue by zioc** [rancher-sandbox/cluster-api-provider-rke2#298]
**What happened:**

In place rolling upgrades of cluster is failing with following rke2controlplane config:

```
spec:
  rolloutStrategy:                                                              
    rollingUpdate:                                                              
      maxSurge: 0                                                               
```

We can observe following logs in rke2 control plane provider logs:

```
E0402 22:15:22.179854       1 rke2controlplane_controller.go:758]  "msg"="RolloutStrategy type is not set to RollingUpdateStrategyType, unable to determine the strategy for rolling out machines" "error"="unknown rollout strategy type \"\"" "cluster-name"="mgmt-1237351673-rke2-capm3-virt" "name"="mgmt-1237351673-rke2-capm3-virt-control-plane" "namespace"="sylva-system"
```

This is a bug in controller, as it [expect RolloutStrategy](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/4756c2a2b5eb6f33180e34baeb2219ddc575ec14/controlplane/internal/controllers/rke2controlplane_controller.go#L749) to be set to [RollingUpdate](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/4756c2a2b5eb6f33180e34baeb2219ddc575ec14/controlplane/api/v1alpha1/rke2controlplane_types.go#L383) whereas the CRD constrains us to use the `rollingUpdate` without capital.

(copied from [downstream issue in sylva project](https://gitlab.com/sylva-projects/sylva-core/-/issues/1118#note_1844249918))

**Comment by zioc** [comment]
In fact it's was just a misconfiguration,  we were missing the `type: RollingUpdate` field:

```
spec:
  rolloutStrategy:
    type: RollingUpdate                                                          
    rollingUpdate:                                                              
      maxSurge: 0   
```
