### ISSUE TITLE
Deployment fails because CAPD cannot set the providerID

### ISSUE THREAD

**Issue by mavynet** [rancher-sandbox/cluster-api-provider-rke2#345]
**What happened:**
Recent Sylva deployments with RKE2 + CAPD is failing because the nodes have the providerID set in the form of `rke2://` and it cannot be updated.

Logs from the CAPD controller show:
```
I0528 04:28:27.291352       1 machine.go:476] "Setting Kubernetes node providerID" controller="dockermachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="DockerMachine" DockerMachine="sylva-system/mgmt-1307843585-rke2-capd-oci-cp-77cefb9d76-r8xwx" namespace="sylva-system" name="mgmt-1307843585-rke2-capd-oci-cp-77cefb9d76-r8xwx" reconcileID="319f0f63-7d53-4cb5-bfb9-3a917793a7ba" Machine="sylva-system/mgmt-1307843585-rke2-capd-oci-control-plane-d8fd2" Machine="sylva-system/mgmt-1307843585-rke2-capd-oci-control-plane-d8fd2" Cluster="sylva-system/mgmt-1307843585-rke2-capd-oci"
E0528 04:28:27.299215       1 dockermachine_controller.go:426] "failed to patch the Kubernetes node with the machine providerID" err="failed to patch node: Node \"mgmt-1307843585-rke2-capd-oci-control-plane-d8fd2\" is invalid: spec.providerID: Forbidden: node updates may not change providerID except from \"\" to valid" controller="dockermachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="DockerMachine" DockerMachine="sylva-system/mgmt-1307843585-rke2-capd-oci-cp-77cefb9d76-r8xwx" namespace="sylva-system" name="mgmt-1307843585-rke2-capd-oci-cp-77cefb9d76-r8xwx" reconcileID="319f0f63-7d53-4cb5-bfb9-3a917793a7ba" Machine="sylva-system/mgmt-1307843585-rke2-capd-oci-control-plane-d8fd2" Machine="sylva-system/mgmt-1307843585-rke2-capd-oci-control-plane-d8fd2" Cluster="sylva-system/mgmt-1307843585-rke2-capd-oci"
```
Failed node spec:
```
  spec:
    podCIDR: 100.72.0.0/24
    podCIDRs:
    - 100.72.0.0/24
    providerID: rke2://mgmt-1307843585-rke2-capd-oci-control-plane-d8fd2
```

**What did you expect to happen:**
Have the correct providerID set

Sylva issue: https://gitlab.com/sylva-projects/sylva-core/-/issues/1288

- rke provider version: v0.2.7
- OS (e.g. from `/etc/os-release`): docker image based on kindest/node:v1.28.9

**Comment by PatrickLaabs** [comment]
That's kind of what I have experienced using the ClusterAPI Provider for Harvester with the v0.3.0 Release von rke2 ControlPlane and Bootstrap Provider.

https://github.com/rancher-sandbox/cluster-api-provider-harvester/issues/38

Using the Version v0.2.2 fixed the issue for me. Maybe this will help to tackle the source of that issue.

**Comment by anmazzotti** [comment]
You need to disable the `cloudController`, this component is what populates the `Node.spec.providerID` field, breaking the CAPI workflow:

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlane
metadata:
  name: my-control-plane
  namespace: default
spec: 
  replicas: 1
  version: "v1.30.1+rke2r1"
  serverConfig:
    disableComponents:
      kubernetesComponents:
        - cloudController
```
