### ISSUE TITLE
RKE2ControlPlane spec.AgentConfig.additionalUserData does not make it to bootstrap Secret

### ISSUE THREAD

**Issue by mmb** [rancher-sandbox/cluster-api-provider-rke2#677]
**What happened:**

To add additional cloud-init to a control plane node I added it to the `spec.template.spec.agentConfig.additionalUserData` field in the `RKE2ControlPlaneTemplate`. It makes it to the `RKE2Config` for the `Machine` but it doesn't get added to the `Machine`'s bootstrap secret.

The same `additionalUserData` works when used on worker nodes via an `RKE2ConfigTemplate`.

**What did you expect to happen:**

I expected the `additionalUserData` to end up in the machine's cloud-init.

**How to reproduce it:**

Create a cluster with this added to the `RKEControlPlane` or `RKEControlPlaneTemplate`:

```
spec:
  template:
    spec:
      agentConfig:
        additionalUserData:
          data:
            bootcmd: |
              - echo test
```

Inspect the bootstrap secret for the machines and see that this isn't in the cloud-init.

**Anything else you would like to add:**

**Environment:**

- rke provider version: 0.14.0
- OS (e.g. from `/etc/os-release`):
