### ISSUE TITLE
privateRegistriesConfig not marshalled correctly

### ISSUE THREAD

**Issue by bvankampen** [rancher-sandbox/cluster-api-provider-rke2#94]
**What happened:**
`privateRegistriesConfig` not marshalled correctly to `registries.yaml`. Therefor the privateregistries are not used.

```
  privateRegistriesConfig:
    mirrors:
      "docker.io":
        endpoint:
          - "https://registry.example.com/v2"
        rewrite:
          "(.*)": "docker.io/$1"
      "quay.io":
        endpoint:
          - "https://registry.example.com/v2"
        rewrite:
          "(.*)": "quay.io/$1"
      "gcr.io":
        endpoint:
          - "https://registry.example.com/v2"
        rewrite:
          "(.*)": "gcr.io/$1"
      "k8s.gcr.io":
        endpoint:
          - "https://registry.example.com/v2"
        rewrite:
          "(.*)": "k8s.gcr.io/$1"
      "ghcr.io":
        endpoint:
          - "https://registry.example.com/v2"
        rewrite:
          "(.*)": "ghcr.io/$1"
```

becomes (Mirrors, Endpoint and Rewrite start with capital letter):

```
Mirrors:
  docker.io:
    Endpoint:
    - https://registry.example.com/v2
    Rewrite:
      (.*): docker.io/$1
  gcr.io:
    Endpoint:
    - https://registry.example.com/v2
    Rewrite:
      (.*): gcr.io/$1
  ghcr.io:
    Endpoint:
    - https://registry.example.com/v2
    Rewrite:
      (.*): ghcr.io/$1
  k8s.gcr.io:
    Endpoint:
    - https://registry.example.com/v2
    Rewrite:
      (.*): k8s.gcr.io/$1
  quay.io:
    Endpoint:
    - https://registry.example.com/v2
    Rewrite:
      (.*): quay.io/$1
```

**What did you expect to happen:**

Correct registries.yaml like:

```
mirrors:
  "docker.io":
    endpoint:
      - "https://registry.example.com/v2"
    rewrite:
      "(.*)": "docker.io/$1"
  "quay.io":
    endpoint:
      - "https://registry.example.com/v2"
    rewrite:
      "(.*)": "quay.io/$1"
  "gcr.io":
    endpoint:
      - "https://registry.example.com/v2"
    rewrite:
      "(.*)": "gcr.io/$1"
  "k8s.gcr.io":
    endpoint:
      - "https://registry.example.com/v2"
    rewrite:
      "(.*)": "k8s.gcr.io/$1"
  "ghcr.io":
    endpoint:
      - "https://registry.example.com/v2"
    rewrite:
      "(.*)": "ghcr.io/$1"
```

**How to reproduce it:**

Create airgapped cluster with private registry

**Anything else you would like to add:**
Fix already, PR will be submitted

**Environment:**

- rke provider version: n/a
- OS (e.g. from `/etc/os-release`): n/a
